- id: '1567669150763'
  alias: Reset_PowerOff_LivingRoom
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.power_living_room
    service: input_boolean.turn_on
- id: '1570737706783'
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ' '
      topic: sonoffs/cmnd/state
    service: mqtt.publish
- id: 3622e863-7639-4234-9cf8-5c0e0280e7ba
  alias: Schlafzimmer Licht Automatik Abend
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '21:30:00'
    before: 04:00:00
    condition: time
  action:
  - entity_id: light.schlafzimmer
    service: light.turn_on
  - delay: 00:05:00
  - data:
      brightness: 100
      color_temp: 350
    entity_id: light.schlafzimmer
    service: light.turn_off
  mode: single
- alias: Schlafzimmer Licht Automatik Morgen
  id: 77be005e-110a-41a5-9ffa-09c184193fd2
  trigger:
    platform: time
    at: 06:00:00
  action:
  - service: light.turn_on
    entity_id: light.bett
  - service: light.turn_on
    entity_id: light.nachttischlampe
  - delay: 00:20:00
  - service: light.turn_off
    entity_id: light.bett
  - service: light.turn_off
    entity_id: light.nachttischlampe
- alias: IFTTT Webhooks
  id: 5af970b6-f1c0-42c2-ac45-ea53f794c97d
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
    service_template: '{{ trigger.event.data.service }}'
- alias: Strom Wohnzimmer ein
  id: 77ea7aa7-aff9-4e2b-841f-f74e3c3f2602
  trigger:
    platform: time
    at: 06:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.mediacenter
- alias: Strom Wohnzimmer aus
  id: b2fe6956-b7fe-4f78-b462-da4c66bff0ca
  trigger:
    platform: time
    at: '23:01:00'
  condition:
  - condition: state
    entity_id: media_player.denon
    state: 'off'
  - condition: state
    entity_id: switch.pc
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nas
  - service: light.turn_off
    entity_id: light.tv_ambiente
  - delay: 00:03:00
  - service: switch.turn_off
    entity_id: switch.mediacenter
- id: 26637951-bdf4-4d08-bcd1-126db09d8379
  alias: Strom aus bei TV aus
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '23:01:00'
    before: 04:00:00
    condition: time
  action:
  - entity_id: switch.nas
    service: switch.turn_off
  - delay: 00:01:30
  - entity_id: light.tv_ambiente
    service: light.turn_off
  - entity_id: light.wohnzimmer
    service: light.turn_off
  - delay: 00:03:00
  - entity_id: switch.mediacenter
    service: switch.turn_off
  mode: single
- alias: Waschmaschine aus
  id: 889d43a2-03a1-4262-b7ab-76807f88502f
  trigger:
    platform: time
    at: '19:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.waschmaschine
- alias: Waschmaschine ein
  trigger:
    platform: time
    at: 07:30:00
  action:
    service: switch.turn_on
    entity_id: switch.waschmaschine
  id: c9648ffdfaf9419faa76456fd79822c5
- id: 2bbc901c-f891-46b8-9779-f2205bae31a3
  alias: Make Snapshot
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
- alias: TV Ambiente Ein
  id: be35e056-0ca3-4b67-ba0c-06545179cc26
  trigger:
    platform: state
    entity_id: media_player.denon
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
  - service: homeassistant.turn_on
    entity_id: light.tv_ambiente
- alias: tv ambiente on after sunset
  id: 4a32d7b3-a790-46b8-a580-b758c1d58c98
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: media_player.denon
    state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.tv_ambiente
- alias: TV Ambiente Aus
  id: fcf90cc1-3f80-4589-814e-88a5c69a583d
  trigger:
    platform: state
    entity_id: media_player.denon
    to: 'off'
  action:
  - delay: 00:02:00
  - service: homeassistant.turn_off
    entity_id: light.tv_ambiente
- alias: washmachine_finished
  id: 47565c9e-ada8-4937-b065-a8c371601de0
  trigger:
    platform: numeric_state
    entity_id: sensor.waschmaschine_energy_power
    below: 10.0
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'on'
  action:
  - service: notify.mobile_app_lukasoneplus
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.mobile_app_HuaweiP30Sarah
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.firetv
    data:
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
  - service: notify.alexa_media
    data:
      target:
      - media_player.esszimmer
      - media_player.kuche
      - media_player.tobias
      - media_player.helga
      - media_player.wohzimmer
      title: Die Wäsche ist fertig
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
      data:
        method: all
        type: announce
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.waschmaschine_aktiv
- alias: washmachine_running
  id: 81b4974f-0191-4bd9-abbb-0256cbe9019a
  trigger:
    platform: numeric_state
    entity_id: sensor.waschmaschine_energy_power
    above: 200
    for:
      seconds: 5
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.waschmaschine_aktiv
- id: '1598713415051'
  alias: Cert Renewal
  description: Starts Lets Encrypt Addon on a daily base
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_restart
  mode: single
- id: '1598723404162'
  alias: Look Door at 9pm
  description: Lock the door at 9pm
  trigger:
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: lock.nuki_hausture
    service: lock.lock
  - data:
      message: Türe wurde versperrt!
    service: notify.mobile_app_lukasoneplus
  - data:
      data:
        method: all
        type: announce
      message: Die Haustüre ist jetzt versperrt. Ich wünsche eine gute Nacht
      target:
      - media_player.esszimmer
      - media_player.kuche
      - media_player.helga
      - media_player.wohzimmer
      title: Haustüre versperrt
    service: notify.alexa_media
  mode: single
- id: '1598723884273'
  alias: Internetspeed is slow
  description: Check if Speedtest is below a specified treshold
  trigger:
  - below: '170'
    entity_id: sensor.speedtest_download
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Die Internetgeschwindigkeit ist gesunken.
      title: Internet ist langsam
    service: notify.mobile_app_lukasoneplus
  mode: single
- id: '1598797452112'
  alias: Nightlight on Motion
  description: Activate Nighlight after 23:00:00 if Motion is detected
  trigger:
  - device_id: f067fe4853c14161a4ffd20c1a3cf1a4
    domain: binary_sensor
    entity_id: binary_sensor.motion_zubau_motion
    platform: device
    type: motion
  condition:
  - after: '23:30:00'
    before: 06:00:00
    condition: time
  action:
  - scene: scene.nachtlicht
  - data:
      message: Nachtlicht wurde aktiviert
    service: notify.mobile_app_lukasoneplus
  mode: single
