- id: '1567669150763'
  alias: Reset_PowerOff_LivingRoom
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.power_living_room
    service: input_boolean.turn_on
- id: 3622e863-7639-4234-9cf8-5c0e0280e7ba
  alias: Schlafzimmer Licht Automatik Abend
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '21:30:00'
    before: 04:00:00
    condition: time
  action:
  - data:
      brightness: 100
      color_temp: 350
    entity_id: light.schlafzimmer
    service: light.turn_on
  - delay: 00:05:00
  - data: {}
    entity_id: light.schlafzimmer
    service: light.turn_off
  - data: {}
    entity_id: light.bad
    service: light.turn_off
  - data: {}
    entity_id: light.kuche
    service: light.turn_off
  - data: {}
    entity_id: light.wohnzimmer
    service: light.turn_off
  - data: {}
    entity_id: light.vorhaus
    service: light.turn_off
  - data: {}
    entity_id: light.zubau
    service: light.turn_off
  - data: {}
    entity_id: light.keller
    service: light.turn_off
  - data: {}
    entity_id: light.tobias
    service: light.turn_off
  - data: {}
    entity_id: light.eli
    service: light.turn_off
  - data: {}
    entity_id: light.schreibtisch
    service: light.turn_off
  - data: {}
    entity_id: light.esstisch
    service: light.turn_off
  - service: light.turn_off
    data: {}
    entity_id: light.hue_outdoor_wall_1
  mode: single
- id: 77be005e-110a-41a5-9ffa-09c184193fd2
  alias: Schlafzimmer Licht Automatik Morgen
  trigger:
  - platform: time
    at: 06:10:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.schlafzimmer
  - delay: 00:07:00
  - service: light.turn_on
    data: {}
    entity_id: light.wohnzimmer
  - service: light.turn_on
    data: {}
    entity_id: light.kuche
  - service: light.turn_on
    data: {}
    entity_id: light.esstisch
  mode: single
- alias: Strom Wohnzimmer ein
  id: 77ea7aa7-aff9-4e2b-841f-f74e3c3f2602
  trigger:
    platform: time
    at: 06:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.mediacenter_relay
- alias: Strom Wohnzimmer aus
  id: b2fe6956-b7fe-4f78-b462-da4c66bff0ca
  trigger:
    platform: time
    at: '23:01:00'
  condition:
  - condition: state
    entity_id: media_player.denon
    state: 'off'
  - condition: state
    entity_id: switch.pc
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nas
  - service: light.turn_off
    entity_id: light.tv_ambiente
  - delay: 00:03:00
  - service: switch.turn_off
    entity_id: switch.mediacenter_relay
- id: 26637951-bdf4-4d08-bcd1-126db09d8379
  alias: Strom aus bei TV aus
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '23:01:00'
    before: 04:00:00
    condition: time
  action:
  - entity_id: switch.nas
    service: switch.turn_off
  - delay: 00:00:45
  - entity_id: switch.mediacenter_relay
    service: switch.turn_off
  mode: single
- id: 889d43a2-03a1-4262-b7ab-76807f88502f
  alias: Waschmaschine aus
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.waschmaschine_relay
  mode: single
- id: c9648ffdfaf9419faa76456fd79822c5
  alias: Waschmaschine ein
  trigger:
  - platform: time
    at: 07:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.waschmaschine_relay
  mode: single
- id: 47565c9e-ada8-4937-b065-a8c371601de0
  alias: washmachine_finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.waschmaschine_leistung
    below: '10'
    for: 0:05:00
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'on'
  action:
  - service: notify.mobile_app_lukasoneplus
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.mobile_app_HuaweiP30Sarah
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.firetv
    data:
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
  - service: notify.alexa_media
    data:
      target:
      - media_player.esszimmer
      - media_player.kuche
      - media_player.tobias
      - media_player.helga
      - media_player.wohzimmer
      title: Die Wäsche ist fertig
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
      data:
        method: all
        type: announce
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.waschmaschine_aktiv
  mode: single
- id: 81b4974f-0191-4bd9-abbb-0256cbe9019a
  alias: washmachine_running
  trigger:
  - platform: numeric_state
    entity_id: sensor.waschmaschine_leistung
    above: '200'
    for: 0:01:00
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.waschmaschine_aktiv
  mode: single
- id: '1598713415051'
  alias: Cert Renewal
  description: Starts Lets Encrypt Addon on a daily base
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_restart
  mode: single
- id: '1598723404162'
  alias: Look Door at 9pm
  description: Lock the door at 9pm
  trigger:
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: lock.nuki_hausture
    service: lock.lock
  - data:
      message: Türe wurde versperrt!
    service: notify.mobile_app_lukasoneplus
  - data:
      data:
        method: all
        type: announce
      message: Die Haustüre ist jetzt versperrt. Ich wünsche eine gute Nacht
      target:
      - media_player.helga
      - media_player.uberall
      title: Haustüre versperrt
    service: notify.alexa_media
  mode: single
- id: '1598723884273'
  alias: Internetspeed is slow
  description: Check if Speedtest is below a specified treshold
  trigger:
  - below: 180
    entity_id: sensor.speedtest_download
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Die Internetgeschwindigkeit ist gesunken.
      title: Internet ist langsam
    service: notify.mobile_app_lukasoneplus
  mode: single
- id: '1598797452112'
  alias: Nightlight on Motion
  description: Activate Nighlight after 23:00:00 if Motion is detected
  trigger:
  - device_id: f067fe4853c14161a4ffd20c1a3cf1a4
    domain: binary_sensor
    entity_id: binary_sensor.motion_zubau_motion
    platform: device
    type: motion
  condition:
  - after: '23:30:00'
    before: 06:00:00
    condition: time
  action:
  - scene: scene.nachtlicht
  - data:
      message: Nachtlicht wurde aktiviert
    service: notify.mobile_app_lukasoneplus
  - delay: 00:01:30
  - data:
      entity_id: lights.all
    service: light.turn_off
  mode: single
- id: '1606050559012'
  alias: Weihnachtsbeleuchtung ein
  description: Weihnachtsbeleuchtung einschalten
  trigger:
  - platform: time
    at: '17:30'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.weihnachtsbeleuchtung_relay
  mode: single
- id: '1606050610750'
  alias: Weichnachtsbeleuchtung aus
  description: Schaltet die Weichnachtsbeleuchtung aus
  trigger:
  - platform: time
    at: '21:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.weihnachtsbeleuchtung_relay
  mode: single
- id: '1606502924060'
  alias: Lueften nicht vergessen
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  - platform: time
    at: '14:30:00'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.esszimmer
      - media_player.kuche
      - media_player.wohzimmer
      title: Die Wäsche ist fertig
      message: Vergiss nicht zu lüften.
      data:
        method: all
        type: announce
  mode: single
- id: '1609144738492'
  alias: Play Spotify in the Morning
  description: Plays a fixed, but dynamic Playlist Spotify in the morning
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.15
    entity_id: media_player.essbereich
  - service: media_player.play_media
    data:
      entity_id: media_player.spotify_lukas
      media_content_id: https://open.spotify.com/playlist/3ZXgf2Z183nYjBl342tyd0
      media_content_type: playlist
  mode: single
- id: '1609242378170'
  alias: BathTurnOnMotion
  description: Turns on the Bath Lights if Motion is detected an LX is under 10
  use_blueprint:
    path: pavax/motion_aware_lights.yaml
    input:
      illuminance_threshold: '10'
      motion_sensor: binary_sensor.motion_bad_motion
      no_motion_wait: '420'
      illuminance_sensor: sensor.motion_bad_light_level
      target_light:
        entity_id: light.bad
- id: '1609259508677'
  alias: OutdoorTurnOnMotion
  description: Turns on the Outdoor Lights if Motion is detected an LX is under 10
  use_blueprint:
    path: pavax/motion_aware_lights.yaml
    input:
      motion_sensor: binary_sensor.hue_outdoor_motion_sensor_1_motion
      illuminance_sensor: sensor.hue_outdoor_motion_sensor_1_light_level
      no_motion_wait: '150'
      illuminance_threshold: '30'
      target_light:
        entity_id: light.hue_outdoor_wall_1
- id: '1609259582484'
  alias: ZubauTurnOnMotion
  description: Turns on the Zubau Lights if Motion is detected an LX is under 10
  use_blueprint:
    path: pavax/motion_aware_lights.yaml
    input:
      illuminance_threshold: '10'
      motion_sensor: binary_sensor.motion_zubau_motion
      illuminance_sensor: sensor.motion_zubau_light_level
      target_light:
        entity_id: light.zubau
- id: '1609259645348'
  alias: VorhausTurnOnMotion
  description: Turns on the Outdoor Lights if Motion is detected an LX is under 10
  use_blueprint:
    path: pavax/motion_aware_lights.yaml
    input:
      illuminance_threshold: '10'
      motion_sensor: binary_sensor.motion_vorhaus_motion
      illuminance_sensor: sensor.motion_vorhaus_light_level
      target_light:
        entity_id: light.vorhaus
- id: '1609259716200'
  alias: BasementTurnOnMotion
  description: Turns on the Outdoor Lights if Motion is detected an LX is under 10
  use_blueprint:
    path: pavax/motion_aware_lights.yaml
    input:
      illuminance_threshold: '50'
      motion_sensor: binary_sensor.motion_keller_motion
      no_motion_wait: '300'
      illuminance_sensor: sensor.motion_keller_light_level
      target_light:
        entity_id:
        - light.keller_1
        - light.keller_2
        - light.kellertreppe
        - light.keller_3
- id: '1609339365291'
  alias: GoodNight Elena
  description: Schaltet die Lampe bei Eli mit einer Transition von 1 Stunde
  trigger:
  - device_id: a7358118e58c46c19442aa2d1cb72cc4
    domain: hue
    platform: device
    type: remote_button_long_release
    subtype: turn_on
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 3600
    entity_id: light.eli
  mode: single
- id: '1609342877715'
  alias: NasOnat20:30
  description: Power On NAS at 20:30 for Backup
  trigger:
  - platform: time
    at: '20:30:00'
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.nas
  mode: single
- id: '1610129606236'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '19:15:00'
      actions:
      - service: notify.mobile_app_lukasoneplus
        data:
          message: 'Low battery warning for: {{sensors}}'
      day: '0'
