- id: '1567669150763'
  alias: Reset_PowerOff_LivingRoom
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: input_boolean.power_living_room
    service: input_boolean.turn_on
- id: '1570737706783'
  alias: Power state on HA start-up
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ' '
      topic: sonoffs/cmnd/state
    service: mqtt.publish
- id: 3622e863-7639-4234-9cf8-5c0e0280e7ba
  alias: Schlafzimmer Licht Automatik Abend
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '21:30:00'
    before: 04:00:00
    condition: time
  action:
  - data:
      brightness: 100
      color_temp: 350
    entity_id: light.schlafzimmer
    service: light.turn_on
  - delay: 00:05:00
  - data: {}
    entity_id: light.schlafzimmer
    service: light.turn_off
  - data: {}
    entity_id: light.bad
    service: light.turn_off
  - data: {}
    entity_id: light.kuche
    service: light.turn_off
  - data: {}
    entity_id: light.wohnzimmer
    service: light.turn_off
  - data: {}
    entity_id: light.vorhaus
    service: light.turn_off
  - data: {}
    entity_id: light.zubau
    service: light.turn_off
  - data: {}
    entity_id: light.keller
    service: light.turn_off
  - data: {}
    entity_id: light.tobias
    service: light.turn_off
  - data: {}
    entity_id: light.eli
    service: light.turn_off
  - data: {}
    entity_id: light.schreibtisch
    service: light.turn_off
  - data: {}
    entity_id: light.esstisch
    service: light.turn_off
  mode: single
- id: 77be005e-110a-41a5-9ffa-09c184193fd2
  alias: Schlafzimmer Licht Automatik Morgen
  trigger:
  - platform: time
    at: 06:10:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.schlafzimmer
  - delay: 00:07:00
  - service: light.turn_on
    data: {}
    entity_id: light.wohnzimmer
  - service: light.turn_on
    data: {}
    entity_id: light.kuche
  - service: light.turn_on
    data: {}
    entity_id: light.esstisch
  mode: single
- alias: Strom Wohnzimmer ein
  id: 77ea7aa7-aff9-4e2b-841f-f74e3c3f2602
  trigger:
    platform: time
    at: 06:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.mediacenter_relay
- alias: Strom Wohnzimmer aus
  id: b2fe6956-b7fe-4f78-b462-da4c66bff0ca
  trigger:
    platform: time
    at: '23:01:00'
  condition:
  - condition: state
    entity_id: media_player.denon
    state: 'off'
  - condition: state
    entity_id: switch.pc
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.nas
  - service: light.turn_off
    entity_id: light.tv_ambiente
  - delay: 00:03:00
  - service: switch.turn_off
    entity_id: switch.mediacenter_relay
- id: 26637951-bdf4-4d08-bcd1-126db09d8379
  alias: Strom aus bei TV aus
  trigger:
  - entity_id: media_player.denon
    platform: state
    to: 'off'
  condition:
  - after: '23:01:00'
    before: 04:00:00
    condition: time
  action:
  - entity_id: switch.nas
    service: switch.turn_off
  - delay: 00:00:45
  - entity_id: switch.mediacenter_relay
    service: switch.turn_off
  mode: single
- id: 889d43a2-03a1-4262-b7ab-76807f88502f
  alias: Waschmaschine aus
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.waschmaschine_relay
  mode: single
- id: c9648ffdfaf9419faa76456fd79822c5
  alias: Waschmaschine ein
  trigger:
  - platform: time
    at: 07:30:00
  action:
  - service: switch.turn_on
    entity_id: switch.waschmaschine_relay
  mode: single
- id: 2bbc901c-f891-46b8-9779-f2205bae31a3
  alias: Make Snapshot
  trigger:
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
- id: 47565c9e-ada8-4937-b065-a8c371601de0
  alias: washmachine_finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.waschmaschine_leistung
    below: '10'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.waschmaschine_aktiv
    state: 'on'
  action:
  - service: notify.mobile_app_lukasoneplus
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.mobile_app_HuaweiP30Sarah
    data:
      message: Räum mich bitte aus, wenn du gerade Zeit hast. Danke.
      title: Die Wäsche ist fertig!
  - service: notify.firetv
    data:
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
  - service: notify.alexa_media
    data:
      target:
      - media_player.esszimmer
      - media_player.kuche
      - media_player.tobias
      - media_player.helga
      - media_player.wohzimmer
      title: Die Wäsche ist fertig
      message: Die Wäsche ist fertig! Räum mich bitte aus, wenn du gerade Zeit hast.
        Danke.
      data:
        method: all
        type: announce
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.waschmaschine_aktiv
  mode: single
- id: 81b4974f-0191-4bd9-abbb-0256cbe9019a
  alias: washmachine_running
  trigger:
  - platform: numeric_state
    entity_id: sensor.waschmaschine_leistung
    above: '200'
    for: 0:01:00
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.waschmaschine_aktiv
  mode: single
- id: '1598713415051'
  alias: Cert Renewal
  description: Starts Lets Encrypt Addon on a daily base
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - data:
      addon: core_letsencrypt
    service: hassio.addon_restart
  mode: single
- id: '1598723404162'
  alias: Look Door at 9pm
  description: Lock the door at 9pm
  trigger:
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: lock.nuki_hausture
    service: lock.lock
  - data:
      message: Türe wurde versperrt!
    service: notify.mobile_app_lukasoneplus
  - data:
      data:
        method: all
        type: announce
      message: Die Haustüre ist jetzt versperrt. Ich wünsche eine gute Nacht
      target:
      - media_player.helga
      - media_player.uberall
      title: Haustüre versperrt
    service: notify.alexa_media
  mode: single
- id: '1598723884273'
  alias: Internetspeed is slow
  description: Check if Speedtest is below a specified treshold
  trigger:
  - below: 180
    entity_id: sensor.speedtest_download
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Die Internetgeschwindigkeit ist gesunken.
      title: Internet ist langsam
    service: notify.mobile_app_lukasoneplus
  mode: single
- id: '1598797452112'
  alias: Nightlight on Motion
  description: Activate Nighlight after 23:00:00 if Motion is detected
  trigger:
  - device_id: f067fe4853c14161a4ffd20c1a3cf1a4
    domain: binary_sensor
    entity_id: binary_sensor.motion_zubau_motion
    platform: device
    type: motion
  condition:
  - after: '23:30:00'
    before: 06:00:00
    condition: time
  action:
  - scene: scene.nachtlicht
  - data:
      message: Nachtlicht wurde aktiviert
    service: notify.mobile_app_lukasoneplus
  - delay: 00:01:30
  - data:
      entity_id: lights.all
    service: light.turn_off
  mode: single
