- platform: ping
  host: 192.168.0.122
  name: Drucker

-  platform: mqtt
   state_topic: "home/433toMQTT"
   name: "motionlivingroom"
   payload_on: "12345387"
   payload_off: "off"
   device_class: motion

-  platform: mqtt
   state_topic: "home/433toMQTT"
   name: "backdoor"
   payload_on: "11910666"
   payload_off: "11910670"
   device_class: door

-  platform: mqtt
   state_topic: "home/433toMQTT"
   name: "frontdoor"
   payload_on: "11762698"
   payload_off: "11762702"
   device_class: door