homeassistant:
  customize: !include customize.yaml
config:
http:
  server_port: 8123
  ip_ban_enabled: True
  login_attempts_threshold: 3
  base_url: !secret ha_url
frontend:
updater:
cloud: !include cloud.yaml
map:
recorder:
  purge_keep_days: 14
discovery:
history:
  include:
    entities:
      - alarm_control_panel.ha_alarm
      - binary_sensor.backdoor
      - binary_sensor.frontdoor
      - sensor.luftfeuchte_esszimmer
      - sensor.luftfeuchte_wohnzimmer
      - sensor.memory_use
      - sensor.processor_use
      - sensor.spannung_waschmaschine
      - sensor.strom_waschmaschine
      - sensor.temperatur_esszimmer
      - sensor.temperatur_wohnzimmer
      - sensor.verbrauch_waschmaschine_heute
logbook:
logger:
  default: info
  logs:
    hass_nabucasa: debug
    snitun: debug
    homeassistant.components.cloud: debug
    homeassistant.components.cloud.iot: debug
sun:
sensor: !include sensor.yaml
media_player: !include mediaplayer.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
shell_command: !include shell_command.yaml
script: !include scripts.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
notify: !include notify.yaml
light: !include light.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
alarm_control_panel: !include alarm.yaml
telegram_bot: !include telegram.yaml
alert: !include alert.yaml
tts:
  - platform: google_translate
    service_name: google_say
    language: 'de'
neato:
  username: !secret neato_username
  password: !secret neato_password
weather:
  - platform: openweathermap
    api_key: !secret openweather_api
    mode: freedaily
system_health:
person:
mobile_app:
#END