homeassistant:
  customize: !include customize.yaml
config:
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
#  base_url: !secret ha_url
frontend:
  themes: !include_dir_merge_named themes
updater:
cloud:
map:
recorder:
  purge_keep_days: 1095
discovery:
history:
logbook:
logger:
  default: info
  logs:
    hass_nabucasa: debug
    snitun: debug
    homeassistant.components.cloud: debug
    homeassistant.components.cloud.iot: debug
sun:
sensor: !include sensor.yaml
media_player: !include mediaplayer.yaml
binary_sensor: !include binary_sensor.yaml
switch: !include switch.yaml
shell_command: !include shell_command.yaml
script: !include scripts.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
notify: !include notify.yaml
light: !include light.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
tts:
  - platform: google_translate
    service_name: google_say
    language: 'de'
weather:
  - platform: openweathermap
    api_key: !secret openweather_api
    mode: freedaily
system_health:
person:
mobile_app:
lock:
  platform: nuki
  host: 192.168.0.52
  token: !secret nuki_token
scene: !include scenes.yaml
nibe:
  systems:
    - system: "98885"
      units:
        - unit: 0
          categories: true
          statuses: true
        - unit: 1
          categories: true
          statuses: true
      climates: true
      water_heaters: true
      fans: false
#      sensors:
#        - 47264
#        - 47265
#        - 10001
#        - fan_speed
spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdbname
  username: !secret influxuser
  password: !secret influxpassword
  max_retries: 3
  default_measurement: state
#END