- platform: androidtv
  name: fernseher
  device_class: androidtv
  host: 192.168.0.92
  state_detection_rules:
    'com.amazon.tv.launcher':
      - 'standby'
    'com.netflix.ninja':
      - 'media_session_state'