- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.motionlivingroom
      to: 'on'
    - platform: state
      entity_id: binary_sensor.frontdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.backdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wc_window
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'armed_away'
  action:
    - service: notify.mobile_app_lukassa40
      data:
        message: "ALARM wurde ausgelöst!"
        title: "Achtung"
    - service: notify.mobile_app_HuaweiP30Sarah
      data:
        message: "ALARM wurde ausgelöst!"
        title: "Achtung"

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: binary_sensor.frontdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.backdoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.wc_window
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'armed_home'
  action:
    - service: notify.mobile_app_lukassa40
      data:
        message: "ALARM wurde ausgelöst!"
        title: "Achtung"
    - service: notify.mobile_app_HuaweiP30Sarah
      data:
        message: "ALARM wurde ausgelöst!"
        title: "Achtung"