- alias: 'arm home no one home'
  trigger:
    - platform: template
      value_template: >
        {%- if is_state('person.lukas', 'not_home') and
                  is_state('person.sarah', 'not_home') -%}
                    true
            {%- else -%}
                    disabled
            {% endif %}
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/Alarmanlage_ein_keiner_daheim'
  action:
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.ha_alarm
        code: !secret alarmcode

- alias: 'disarm if someone comes home'
  trigger:
    platform: template
    value_template: >
      {%- if is_state('person.lukas', 'not_home') and
                is_state('person.sarah', 'not_home') -%}
                  disabled
          {%- else -%}
                  true
          {% endif %}
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.ha_alarm
        code: !secret alarmcode
