- alias: temp_wz_low
  trigger:
    platform: numeric_state
    entity_id: sensor.temperatur_wohnzimmer
    below: 20.00
  action:
    - service: notify.mobile_app_lukassa40
      data_template:
        message: "Temperatur im Wohnzimmer ist niedrig! Temperatur ist {{ states.sensor.temperatur_wohnzimmer.state }} 째C"
        title: "Brrr..."
    - service: notify.mobile_app_mi_a3
      data_template:
        message: "Temperatur im Wohnzimmer ist niedrig! Temperatur ist {{ states.sensor.temperatur_wohnzimmer.state }} 째C"
        title: "Brrr..."

- alias: temp_wz_high
  trigger:
    platform: numeric_state
    entity_id: sensor.temperatur_wohnzimmer
    above: 23.00
  action:
    - service: notify.mobile_app_lukassa40
      data_template:
        message: "Temperatur im Wohnzimmer ist hoch! Temperatur ist {{ states.sensor.temperatur_wohnzimmer.state }} 째C"
        title: "Ich schwitze..."
    - service: notify.mobile_app_mi_a3
      data_template:
        message: "Temperatur im Wohnzimmer ist hoch! Temperatur ist {{ states.sensor.temperatur_wohnzimmer.state }} 째C"
        title: "Ich schwitze..."

- alias: firetv_alarm_armedhome
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'armed_home'
  action:
    service: notify.firetv
    data:
      message: 'Alarmanlage ist aktiv'

- alias: firetv_alarm_aus
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'disarmed'
  action:
    service: notify.firetv
    data:
      message: 'Alarmanlage ist aus'