- alias: 'Strom Wohnzimmer ein'
  trigger:
    platform: time
    at: '06:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.mediacenter

- alias: 'Strom Wohnzimmer aus'
  trigger:
    platform: time
    at: '23:01:00'
  condition:
    - condition: state
      entity_id: media_player.denon
      state: 'off'
    - condition: state
      entity_id: switch.pc
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.nas
    - service: light.turn_off
      entity_id: light.tv_ambiente
    - delay: '00:03:00'
    - service: switch.turn_off
      entity_id: switch.mediacenter

- alias: 'Strom aus bei TV aus'
  trigger:
    platform: state
    entity_id: media_player.denon
    to: 'off'
  condition:
    - condition: state
      entity_id: switch.pc
      state: 'off'
    - condition: time
      after: '23:01'
      before: '04:00'
  action:
    - service: switch.turn_off
      entity_id: switch.nas
    - delay: '00:01:30'
    - service: light.turn_off
      entity_id: light.tv_ambiente
    - delay: '00:03:00'
    - service: switch.turn_off
      entity_id: switch.mediacenter

- alias: 'Strom aus bei PC aus'
  trigger:
    platform: state
    entity_id: switch.pc
    to: 'off'
  condition:
    - condition: state
      entity_id: media_player.denon
      state: 'off'
    - condition: time
      after: '23:01'
      before: '04:00'      
  action:
    - service: switch.turn_off
      entity_id: switch.nas
    - delay: '00:01:30'
    - service: light.turn_off
      entity_id: light.tv_ambiente
    - delay: '00:03:00'
    - service: switch.turn_off
      entity_id: switch.mediacenter

- alias: 'arm home on'
  trigger:
   -  platform: time
      at: '21:00:00'
   - platform: event
     event_type: telegram_command
     event_data:
       command: '/Alarmanlage_jemand_daheim'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        entity_id: alarm_control_panel.ha_alarm
        code: !secret alarmcode

- alias: 'disable alarm'
  trigger:
    - platform: time
      at: '06:00:00'
    - platform: event
      event_type: telegram_command
      event_data:
        command: '/Alarmanlage_aus'
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.ha_alarm
        code: !secret alarmcode

- alias: 'Waschmaschine aus'
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.waschmaschine_aktiv
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.waschmaschine

- alias: 'Waschmaschine ein'
  trigger:
    platform: time
    at: '07:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.waschmaschine

- alias: 'Weihnachtsbeleuchtung aus'
  trigger:
    platform: time
    at: '21:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.temp

- alias: 'Weihnachtsbeleuchtung ein'
  trigger:
    platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: switch.temp
    
- id: 'createsnapshot'
  alias: Make Snapshot
  trigger:
  - platform: time
    at: '03:00:00'
  condition: []
  action:
  - service: hassio.snapshot_full
    data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}