- alias: 'TV Ambiente Ein'
  trigger:
    platform: state
    entity_id: media_player.denon
    to: 'on'
  condition:
    condition: sun
    after: 'sunset'
  action:
    - service: homeassistant.turn_on
      entity_id: light.tv_ambiente

- alias: 'tv ambiente on after sunset'
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: media_player.denon
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.tv_ambiente
    
- alias: 'TV Ambiente Aus'
  trigger:
    platform: state
    entity_id: media_player.denon
    to: 'off'
  action:
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: light.tv_ambiente