esphome:
  name: waschmaschine
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: !secret ssid
  password: !secret wifi_password

  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

api:

logger:
  baud_rate: 0
ota:

#uart:
#  rx_pin: RX
#  baud_rate: 4800

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    current:
      name: "Waschmaschine Ampere"
    voltage:
      name: "Waschmaschine Spannung"
      filters:
        - calibrate_linear:
          - 0.0 -> 0.0
          - 202.87440 -> 230.01
    power:
      name: "Waschmaschine Leistung"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Waschmaschine Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Waschmaschine Status"

switch:
  - platform: gpio
    name: "Waschmaschine Relay"
    pin: GPIO12
    id: relay

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  - platform: monochromatic
    name: "Waschmaschine LED"
    output: blue_led