---
name: Home Assistant CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 11 * * *

jobs:
  home_assistant_stable:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./stubs/* ./
      - name: Create SSL-Dummy File
        run: touch ./ssl/fullchain.pem
      - name: Create SSL-Key-Dummy File
        run: touch ./ssl/privkey.pem
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./ --script check_config --files --secrets --info all
  home_assistant_beta:
    runs-on: ubuntu-latest
    steps: 
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy stub files into configuration folder
        run: cp -R ./stubs/* ./
      - name: Create SSL-Dummy File
        run: touch ./ssl/fullchain.pem
      - name: Create SSL-Key-Dummy File
        run: touch ./ssl/privkey.pem
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: python -m homeassistant --config ./ --script check_config --files --secrets --info all